#!/usr/bin/env bash
# This file is part of Xenta OS  Organization - Project Management.
# 
# txt2md is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# txt2md is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# sed -i 's/original/new/g' file.txt
figle getscreenshot
source=$HOME/Pictures
target=$HOME/xentaos/komunikasi/project/kulgram/linuxser/next/screenshot
cd $source
cp Screenshot**.png $target
