#!/usr/bin/env bash
figlet decrypt
SAVEIF=$IFS
IFS=$(echo -en "\n\b")
for file in $(ls Logchat*gpg)
do
  name=${file%%.gpg}
  uid=root@dev.xentaos.org
  gpg --output $name.pdf --decrypt --recipient $uid $name.gpg
done
IFS=$(echo -en "\n\b")
for file in $(ls Screenshot*gpg)
do
  name=${file%%.gpg}
  uid=root@dev.xentaos.org
  gpg --output $name.png --decrypt --recipient $uid $name.gpg
done
IFS=$(echo -en "\n\b")
for file in $(ls pin*gpg)
do
  name=${file%%.gpg}
  uid=root@dev.xentaos.org
  gpg --output $name.txt --decrypt --recipient $uid $name.gpg
done
