#!/usr/bin/env bash
figlet encrypt
SAVEIF=$IFS
IFS=$(echo -en "\n\b")
for file in $(ls *pdf)
do
  name=${file%%.pdf}
  uid=root@dev.xentaos.org
  gpg --output $name.gpg --encrypt --recipient $uid $name.pdf
done
IFS=$(echo -en "\n\b")
for file in $(ls *png)
do
  name=${file%%.png}
  uid=root@dev.xentaos.org
  gpg --output $name.gpg --encrypt --recipient $uid $name.png
done
IFS=$(echo -en "\n\b")
for file in $(ls *txt)
do
  name=${file%%.txt}
  uid=root@dev.xentaos.org
  gpg --output $name.gpg --encrypt --recipient $uid $name.txt
done
